### ISSUE TITLE
[Bug] Frame rotation moves into other blocks

### ISSUE THREAD

**Issue by Lordmau5** [planetguy32/RemainInMotion#160]
As clearly visible in the following video, the rotation happens, even though it should not.
The frame blocks are being replaced at the blocks on that position...
https://i.lordmau5.com/1437566083-54.mp4

**Comment by da3dsoul** [comment]
Gah, not again!

**Comment by Lordmau5** [comment]
I have a feeling that the frames are not being taken into account at the rotation.
I also assume no one will ever rotate into the inside on purpose :p

**Comment by da3dsoul** [comment]
Finally looked into it thoroughly. It appears I broke it in code cleanup about six months ago. Weird because I spent a lot of time on that. I'll fix it tomorrow, assuming I get my workspace functional again. Trying to get planet guy lib working properly with a clean automated build setup, so it's not as awkward.

**Comment by da3dsoul** [comment]
I haven't tested it, because an issue with FMP prevents it from building. I did look through it and I think I fixed it once more.

**Comment by da3dsoul** [comment]
mk I'll test it sometime now.

**Comment by da3dsoul** [comment]
Right! I was going to do that...

**Comment by da3dsoul** [comment]
Ok! It works
