### ISSUE TITLE
Immersive Engineering

### ISSUE THREAD

**Issue by Nentify** [planetguy32/RemainInMotion#161]
When moving a multiblock with IE, some of the blocks duplicate. It left a trail of light mechanical blocks, dropping one each time it moved.

![](http://i.nentify.me/XpaQCKhN.png)
![](http://i.nentify.me/k6gwAmz9.png)

Also, is there an easy way to stop the continuous motion?

**Comment by Nentify** [comment]
![](http://i.nentify.me/0BIWzxAS.png)

This happens too when I move part of an IE multi-block, but when broken no blocks are duplicated, a slice of the machine is just missing.

**Comment by planetguy32** [comment]
It certainly shouldn't be leaving behind blocks. I'll dig into IE to see why that happens.

You can stop continuous motion by putting a block in front, and IIRC there's a configuration option to insert a delay between continuous moves, but otherwise not really.

I'd expect moving parts of a multiblock to be a bit weird, but I'll see if I can make it look better.

**Comment by BluSunrize** [comment]
It's a friggin multiblock, you're not supposed to move it. It's gonna break in all sorts of ways. just stop while your world is still uncorrupted .-.

**Comment by da3dsoul** [comment]
Do you know who I am? I have a history of ****ing with everyone else's mod and leaving a trail of what "you're not supposed to" do, and it always works, because I'm me.

**Comment by planetguy32** [comment]
I've had good luck moving excavators in my test worlds, and this is the only issue.

**Comment by da3dsoul** [comment]
My point exactly!!

**Comment by planetguy32** [comment]
As of f3720e08b517c3961e73d29ec8d9f659cf897e93, it suppresses item drops produced while picking up blocks. No IE dependency is necessary.

IE seems to render its multiblock structures all at once from a master block, so to render them piecemeal we would need to include all its models and assets in a suitable form, and that's infinitely more trouble than it's worth.

**Comment by da3dsoul** [comment]
I think it should need to encase the entire multiblock if it is to move it. There is already api for it too.

**Comment by BluSunrize** [comment]
Okay, be stupid about it then. Go ahead, break your game. Just know that any attempt to move wire connectors will fuck royally with the energy transport system.

**Comment by planetguy32** [comment]
When I tested it, moving a connector would make any attached wires disappear, but it wouldn't crash or anything.

**Comment by BluSunrize** [comment]
Incorrect. It might not properly remove the entry for the list of available connections, leading to issues when using that list, e.g. sending power to a block that isn't there or filling the list with unnecessary ghost entries.
It's these complexities that made Mojang chose to have pistons not push TileEntities, because complex blocks like those are not meant to move.

**Comment by planetguy32** [comment]
When picking up a TileEntity, the invalidate() method is called, just like when the block is removed for any other reason, so Immersive Engineering's normal cleanup code runs. (That was the cause of the bug here: we hadn't accounted for IE using invalidate() to drop the block as items. Now RemIM sets World.isRestoringSnapshots to true to suppress item drops.)

**Comment by planetguy32** [comment]
0569890d5acba0ef009ba4f15eff02be2b234936 adds integration code to re-connect wires if a connector moves. 

Since invalidate() is called on TileEntities as they are picked up, they take apart their connections. (They also attempt to drop themselves as items, but because we set world.restoringBlockSnapshots=true the items aren't spawned). The integration code copies the connections to the connector's NBT tag when picking them up and sets them up again once the blocks are in place.

**Comment by BluSunrize** [comment]
You are missing my point entirely. Actually you probably get it, you just chose to blatantly ignore it. I do not intend for IE blocks to be moveable. I proved that only recently by including the BloodMagic event for cancelling Teleposers. As such I find the meddling you do with my and Minecraft's code to make it work really obnoxious. I do not endorse this mod to be used to transport IE machinery.

**Comment by Nentify** [comment]
RemainInMotion 2.8.1, it is still duping multiblock blocks (easiest to setup and test is the lightning rod)

**Comment by Nentify** [comment]
I guess I need .3 ignore me
