### ISSUE TITLE
Problem: seems like a world gen conflict

### ISSUE THREAD

**Issue by lightning02** [planetguy32/RemainInMotion#184]
Hello, I found this problem adding blood magic, seems like a world gen conflict that spam in the console and make the game a bit laggy, is this a problem of blood magic (alchemicalwizardryBooks) or remain in motion (PlanetGuy Lib)?
How should I proceed?

The latest log is: http://pastebin.com/AvvWbyKB
The  fml-client-latest.log is: https://copy.com/lIJMB7KzBfQutl2R/fml-client-latest.log?download=1 (It was a bit too long for pastebin)

**Comment by planetguy32** [comment]
The console messages you point out there comes from reloading resource packs, so they won't cause any slowdown except when you're changing resource packs. Your MAtmos does seem to be having trouble finding all its resources, but I don't think that accounts for anything noticeable.

For finding what causes lag, I'd recommend a profiling tool like VisualVM - it'll tell you exactly how Minecraft spends its CPU time. Barring that, here are some wild guesses as to what might be going on:

I notice you assign a lot of RAM to Minecraft. This can actually be harmful to performance, because Java's garbage collector has to check more RAM to see if it's still in use, taking a longer time to do so.

It could be that world-generation is actually slow. You have a very large modpack, and each mod that needs ores and structures adds a step to world generation, making the process take longer. (PlanetguyLib, and I think Blood Magic as well, don't add world-generation structures, so they won't cause any world-generation lag.)

If world-gen lag is a game-breaking problem, there are tools that will pre-generate the world, so your computer can do the hard work of generating chunks without interrupting your play.

From your logs, it looks like your game's simulation part is holding up pretty well - it doesn't ever complain in the log that it skipped ticks.
